### ISSUE TITLE
sea-orm-cli overrides entities on generate

### ISSUE THREAD

**Issue by andres-movl** [mgugger/actix-web-sample-app#4]
Not an issue per-se with actix-admin, but wondering if there's any support or plans to support a --with-serde type of flag for sea-orm-cli generate entity command which provides by default all actix-admin derives? Otherwise any change in the migrations overrides any manual changes made on the entities.

**Comment by mgugger** [comment]
Hi Andres

I don't have any ideas on how this could be solved, but I'd be open for suggestions.

Since actix-admin depends not only on the entity structure in the DB but also on struct field attributes (e.g. for dropdowns, which columns are searchable by default, html input classes, etc.), I guess any way of generating the entities directly from the DB through sea-orm-cli will only yield a partial view. That actix-admin information still will need to be stored somewhere. 

As rust does not have struct inheritance, I don't see a way how to combine sea-orm-cli without having to split actix-admin into separate structs than the ones generated from the sea-orm-cli. Splitting in theory would be possible (having 2 structs, one for sea-orm and one for actix-admin). It would however require reimplementing the two traits ([ActixAdminViewModelTrait](https://github.com/mgugger/actix-admin/blob/main/src/view_model.rs#L12-L37) and [ActixAdminModelTrait](https://github.com/mgugger/actix-admin/blob/main/src/model.rs#L17-L29) instead of using the Derive functions) for the actix-admin struct. The implementations would then reference the sea-orm struct, so something like this:
```rust
struct ActixAdminEntity {#actix_admin_definitions}

struct SeaOrmEntity{#autogenerated_orm_entities}

impl ActixAdminViewModelTrait for ActixAdminEntity {}

impl ActixAdminModelTrait for ActixAdminEntity {}
```
 
Probably with a generic ActixAdminEntity<SeaOrmEntity> struct the derives could be included in the macros. It would require some rework however.
